## Latex Shit
theta: $\theta$ <br/>
alfa:  $\alpha$ <br/>
gamma: $\gamma$ <br/>
omicron: $\omicron$ <br/>
epsilon: $\epsilon$ <br/>
pi: $\pi$ Pi: $\Pi$ <br/>
mu: $\mu$

\begin{equation} \label{eq:2}
	2CO + O_2 \rightarrow 2CO_2
\end{equation}
\begin{equation} \label{eq:hflux}
	q = h\Delta T_{ln}, \qquad \Delta T_{ln} = \frac{(T_1 - T_s) - (T_2 - T_s)}{\ln (T_1 - T_s) - \ln (T_2 - T_s)}.
\end{equation}

In [17]:
import numpy as np

In [40]:
v1 = np.array([[1,2,3]])
v2 = np.array([[4],[5],[1]])
print(v1)
print("----------")
print(v2)

[[1 2 3]]
----------
[[4]
 [5]
 [1]]


In [41]:
print("v1:s shape is:")
print(v1.shape)
print("----------")
print("v2:s shape is:")
print(v2.shape)

v1:s shape is:
(1, 3)
----------
v2:s shape is:
(3, 1)


In [42]:
print("multiplying a 1x3-matrix with a 3x1-matrix")
print("thus (1x3)*(3x1) yields (1x1), a scalar")
dot1 = np.dot(v1,v2)
print(dot1)

multiplying a 1x3-matrix with a 3x1-matrix
thus (1x3)*(3x1) yields (1x1), a scalar
[[17]]


In [43]:
print("multiplying a 3x1-matrix with a 1x3-matrix")
print("thus (3x1)*(1x3) = (3x3), a 3x3-matrix")
dot2 = np.dot(v2,v1)
print(dot2)

multiplying a 3x1-matrix with a 1x3-matrix
thus (3x1)*(1x3) = (3x3), a 3x3-matrix
[[ 4  8 12]
 [ 5 10 15]
 [ 1  2  3]]
